### ISSUE TITLE
[Question] Sample is broken and does this support SqlServer out of the box? I had some issues with running the sample

### ISSUE THREAD

**Issue by jeffward01** [fluxera/Fluxera.Extensions.Hosting.Modules#59]
Hello!

Very cool code!! Reminds me of a better version of the module system from `abp` or `aspnetboilerplate` - your code is great!  I could not understand how to implement or worth with `Fluxera.Extensions.Hosting.Modules` to be honest, so I ran the sample code.

The sample code was throwing an error due to a Mass Transit issue with the `InMemory` database not being registered, something like that.

I was looking to set up SqlServer, and my code for that I put here:

https://github.com/fluxera/Fluxera.Extensions.Hosting.Modules/blob/main/samples/Example.Infrastructure/ExampleInfrastructureModule.cs

```csharp
	/// <summary>
	///     The infrastructure module of the component.
	/// </summary>
	[PublicAPI]
	[DependsOn<ExampleDomainModule>]
	[DependsOn<InMemoryMessagingModule>]
	[DependsOn<TransactionalOutboxModule<ExampleDbContext>>]
	[DependsOn<EntityFrameworkCorePersistenceModule>]
	[DependsOn<ConfigurationModule>]
	public sealed class ExampleInfrastructureModule : ConfigureServicesModule
	{

		private readonly string _msSqlServerConnectionString =
			@"Server=.\\SQLExpress;Database=HostingModules_SandboxAppDb;Trusted_Connection=True;Encrypt=false";
		
		
		/// <inheritdoc />
		public override void ConfigureServices(IServiceConfigurationContext context)
		{
			// Add the repository contributor for the 'Default' repository.
			context.Services.AddRepositoryContributor<RepositoryContributor>("Default");

			// Add the repository context contributor for the 'Default' repository.
			context.Services.AddRepositoryContextContributor<RepositoryContextContributor>("Default");

			// Add repositories.
			context.Log("AddRepositories", services =>
				services.TryAddTransient<IExampleRepository, ExampleRepository>());

			RegisterDbContextMsSqlServer(context.Services);
			//	context.Services.AddDbContext<ExampleDbContext>();
		}


		private void RegisterDbContextMsSqlServer(IServiceCollection services)
		{
						
			services.AddDbContextFactory<ExampleDbContext>(
				options => options.UseSqlServer(_msSqlServerConnectionString), ServiceLifetime.Scoped);

			services.AddDbContext<ExampleDbContext, ExampleDbContext>(
				options => { options.UseSqlServer(_msSqlServerConnectionString, sqlServerOptions => 
					{ sqlServerOptions.MigrationsAssembly(typeof(ExampleDbContext).Assembly.FullName); }); },
				ServiceLifetime.Scoped,
				ServiceLifetime.Scoped);
		}
	}
```

I'm sure I could have made my own module, and done better with my implementation - but I just wanted to get it running. 

```bash
[15:07:14 INF] Loaded module: ExampleService.ExampleServiceModule
[15:07:14 INF] Global Subscription ID: FF13323CC41DCAF53451A4B3EEBD16B3 (Development, ExampleService)
[15:07:14 INF] Configured endpoint example.messagingapi.consumers.example-added__FF13323CC41DCAF53451A4B3EEBD16B3, Consumer: Example.MessagingApi.Consumers.ExampleAddedConsumer
[15:07:14 INF] Configured endpoint example.messagingapi.consumers.example-updated__FF13323CC41DCAF53451A4B3EEBD16B3, Consumer: Example.MessagingApi.Consumers.ExampleUpdatedConsumer
[15:07:14 INF] Running host using ConsoleLifetime.
[15:07:14 INF] Host configured in 909 ms.
[15:07:14 INF] Bus started: loopback://localhost/
[15:07:14 INF] Now listening on: https://localhost:5001
[15:07:14 INF] Now listening on: http://localhost:5000
[15:07:14 INF] Application started. Press Ctrl+C to shut down.
[15:07:14 INF] Hosting environment: Development
[15:07:14 INF] Content root path: C:\Dev\Github\ClonedOrgs\Fluxera\Fluxera.Extensions.Hosting.Modules\samples\ExampleService
[15:07:25 ERR] An error occurred using the connection to database 'Aeonic_HostingModules_SandboxAppDb' on server '.\\SQLExpress'.
[15:07:25 ERR] ProcessMessageBatch faulted
System.InvalidOperationException: Instance failure.
   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, SqlConnectionString connectionOptions, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at MassTransit.EntityFrameworkCoreIntegration.BusOutboxDeliveryService`1.<>c__DisplayClass10_0.<<DeliverOutbox>g__Execute|0>d.MoveNext() in /_/src/Persistence/MassTransit.EntityFrameworkCoreIntegration/EntityFrameworkCoreIntegration/BusOutboxDeliveryService.cs:line 105
--- End of stack trace from previous location ---
   at MassTransit.EntityFrameworkCoreIntegration.BusOutboxDeliveryService`1.DeliverOutbox(CancellationToken cancellationToken) in /_/src/Persistence/MassTransit.EntityFrameworkCoreIntegration/EntityFrameworkCoreIntegration/BusOutboxDeliveryService.cs:line 167
   at MassTransit.EntityFrameworkCoreIntegration.BusOutboxDeliveryService`1.DeliverOutbox(CancellationToken cancellationToken) in /_/src/Persistence/MassTransit.EntityFrameworkCoreIntegration/EntityFrameworkCoreIntegration/BusOutboxDeliveryService.cs:line 184
   at MassTransit.EntityFrameworkCoreIntegration.BusOutboxDeliveryService`1.DeliverOutbox(Int32 resultLimit, CancellationToken cancellationToken) in /_/src/Persistence/MassTransit.EntityFrameworkCoreIntegration/EntityFrameworkCoreIntegration/BusOutboxDeliveryService.cs:line 81
   at MassTransit.Util.RequestRateAlgorithm.RunRequest(RequestCallback requestCallback, CancellationToken cancellationToken) in /_/src/MassTransit.Abstractions/Util/RequestRateAlgorithm.cs:line 149
   at MassTransit.Util.RequestRateAlgorithm.Run(RequestCallback requestCallback, CancellationToken cancellationToken) in /_/src/MassTransit.Abstractions/Util/RequestRateAlgorithm.cs:line 142
   at MassTransit.EntityFrameworkCoreIntegration.BusOutboxDeliveryService`1.ExecuteAsync(CancellationToken stoppingToken) in /_/src/Persistence/MassTransit.EntityFrameworkCoreIntegration/EntityFrameworkCoreIntegration/BusOutboxDeliveryService.cs:line 63
[15:07:25 ERR] An error occurred using the connection to database 'Aeonic_HostingModules_SandboxAppDb' on server '.\\SQLExpress'.
[15:07:25 ERR] An exception occurred while iterating over the results of a query for context type 'Example.Infrastructure.ExampleDbContext'.
System.InvalidOperationException: Instance failure.
```

My ExamlpeContext.cs looked like:

```csharp
[PublicAPI]
	public sealed class ExampleContext : EntityFrameworkCoreContext
	{
		private readonly ILogger<ExampleContext> logger;
		private readonly IDatabaseConnectionStringProvider databaseConnectionStringProvider;
		private readonly IDatabaseNameProvider databaseNameProvider;

		public ExampleContext(
			ILogger<ExampleContext> logger,
			IDatabaseNameProvider databaseNameProvider = null,
			IDatabaseConnectionStringProvider databaseConnectionStringProvider = null)
		{
			this.logger = logger;
			this.databaseNameProvider = databaseNameProvider;
			this.databaseConnectionStringProvider = databaseConnectionStringProvider;
		}

		/*/// <inheritdoc />
		protected override void ConfigureOptions(InMemoryContextOptions options)
		{
			RepositoryName repositoryName = new RepositoryName("Default");

			string databaseName = this.databaseNameProvider?.GetDatabaseName(repositoryName);
			string connectionString = this.databaseConnectionStringProvider?.GetConnectionString(repositoryName);

			this.logger.LogInformation("Using database name: '{DatabaseName}'.", databaseName);
			this.logger.LogInformation("Using connection string: '{ConnectionString}'.", connectionString);

			options.Database = databaseName;
		}*/

		/// <inheritdoc />
		protected override void ConfigureOptions(EntityFrameworkCoreContextOptions options)
		{
			RepositoryName repositoryName = new RepositoryName("Default");

			string databaseName = this.databaseNameProvider?.GetDatabaseName(repositoryName);
			string connectionString = this.databaseConnectionStringProvider?.GetConnectionString(repositoryName);
			this.logger.LogInformation("Using database name: '{DatabaseName}'.", databaseName);
			this.logger.LogInformation("Using connection string: '{ConnectionString}'.", connectionString);
			options.UseDbContext<ExampleDbContext>();
			
 
		}		
		
		
	}
```

The InMemory sample configuration was also throwing a similar error.

I know your busy, no rush at all.  Here are my questions:

1. The error for the `InMemory` database (when you run the sample with no changes in code) - the error was a 'ProviderConfiguration' error using OutboxDeliveryService by MassTransist.  I can take a look at this, but can you point me to where the issue would be so that I could examine it? 

2.  Does this support SqlServer, or do I need to add it like I did in my example above?

----

I think this is probably the best implementation of module based integrations that I have seen. I would love to contribute to [Fluxera](https://github.com/fluxera )anyway that you guys need 

Thank you!

**Comment by mgernand** [comment]
Hi!

> Very cool code!! Reminds me of a better version of the module system from abp or aspnetboilerplate - your code is great! I could not understand how to implement or worth with Fluxera.Extensions.Hosting.Modules to be honest, so I ran the sample code.

Thank you. Years ago I had to use ABP in a customer project but we never really were able to bend it the way we needed. But it surly has it's roots there.

The current version, including the documentation, is work in progress. I hope to add some better documentation soon. But the example should not crash.

> The error for the InMemory database (when you run the sample with no changes in code) - the error was a 'ProviderConfiguration' error using OutboxDeliveryService by MassTransist. I can take a look at this, but can you point me to where the issue would be so that I could examine it?

I have some changes that are not already committed. I will look at it the next days and maybe then I know where to point you. 

> Does this support SqlServer, or do I need to add it like I did in my example above?

The example only supports InMemory DB at the moment. But switching to SQL Server should work.

> I think this is probably the best implementation of module based integrations that I have seen. 

Thank you very much. I appreciate it.

> I would love to contribute

Sound great. Help is always welcome. Maybe we find some time to chat 1:1.

**Comment by mgernand** [comment]
The sample now supports SQL Server. I added migrations and configuration for it.
